import { useState } from "react";
import {
  FileText,
  Download,
  Plus,
  ShieldCheck,
  AlertTriangle,
  Activity,
  Clock,
  X,
} from "lucide-react";

function Reports() {
  const [reports, setReports] = useState([
    {
      id: 1,
      name: "Monthly Security Report",
      type: "Security Overview",
      date: "September 2026",
      status: "Ready",
    },
    {
      id: 2,
      name: "Threat Detection Report",
      type: "Threat Analysis",
      date: "September 2026",
      status: "Ready",
    },
    {
      id: 3,
      name: "Cloud Activity Report",
      type: "Activity Summary",
      date: "September 2026",
      status: "Ready",
    },
  ]);

  const [showModal, setShowModal] = useState(false);

  const [reportType, setReportType] = useState(
    "Security Overview"
  );

  const handleGenerateReport = () => {
    const newReport = {
      id: Date.now(),
      name: `${reportType} Report`,
      type: reportType,
      date: new Date().toLocaleDateString("en-US", {
        month: "long",
        year: "numeric",
      }),
      status: "Ready",
    };

    setReports((currentReports) => [
      newReport,
      ...currentReports,
    ]);

    setShowModal(false);
  };

  const handleDownload = (report) => {
    const reportContent = `
CloudGuard - AI Cloud Security Monitor
=======================================

Report: ${report.name}
Type: ${report.type}
Date: ${report.date}
Status: ${report.status}

Security Overview
-----------------
Security Score: 87%
Active Threats: 12
Security Alerts: 28
Cloud Resources: 146

This report was generated by CloudGuard.
`;

    const blob = new Blob([reportContent], {
      type: "text/plain",
    });

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");
    link.href = url;
    link.download = `${report.name
      .toLowerCase()
      .replace(/\s+/g, "-")}.txt`;

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex flex-col justify-between gap-4 md:flex-row md:items-center">
        <div>
          <p className="text-sm text-cyan-400">
            Security Reports
          </p>

          <h1 className="mt-1 text-3xl font-bold text-white">
            Reports
          </h1>

          <p className="mt-2 text-sm text-slate-400">
            Generate and review security reports for your
            cloud environment.
          </p>
        </div>

        <button
          onClick={() => setShowModal(true)}
          className="inline-flex items-center justify-center gap-2 rounded-xl bg-cyan-500 px-5 py-3 text-sm font-semibold text-slate-950 transition hover:bg-cyan-400"
        >
          <Plus className="h-4 w-4" />
          Generate Report
        </button>
      </div>

      {/* Overview Cards */}
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <div className="rounded-2xl border border-white/10 bg-slate-900/60 p-5">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-slate-400">
                Total Reports
              </p>

              <p className="mt-2 text-2xl font-bold text-white">
                {reports.length}
              </p>
            </div>

            <div className="rounded-xl bg-cyan-400/10 p-3">
              <FileText className="h-5 w-5 text-cyan-400" />
            </div>
          </div>
        </div>

        <div className="rounded-2xl border border-white/10 bg-slate-900/60 p-5">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-slate-400">
                Security Score
              </p>

              <p className="mt-2 text-2xl font-bold text-white">
                87%
              </p>
            </div>

            <div className="rounded-xl bg-emerald-400/10 p-3">
              <ShieldCheck className="h-5 w-5 text-emerald-400" />
            </div>
          </div>
        </div>

        <div className="rounded-2xl border border-white/10 bg-slate-900/60 p-5">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-slate-400">
                Active Threats
              </p>

              <p className="mt-2 text-2xl font-bold text-white">
                12
              </p>
            </div>

            <div className="rounded-xl bg-red-400/10 p-3">
              <AlertTriangle className="h-5 w-5 text-red-400" />
            </div>
          </div>
        </div>

        <div className="rounded-2xl border border-white/10 bg-slate-900/60 p-5">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-slate-400">
                Cloud Resources
              </p>

              <p className="mt-2 text-2xl font-bold text-white">
                146
              </p>
            </div>

            <div className="rounded-xl bg-blue-400/10 p-3">
              <Activity className="h-5 w-5 text-blue-400" />
            </div>
          </div>
        </div>
      </div>

      {/* Reports */}
      <div className="rounded-2xl border border-white/10 bg-slate-900/60">
        <div className="flex items-center justify-between border-b border-white/10 px-6 py-5">
          <div>
            <h2 className="font-semibold text-white">
              Generated Reports
            </h2>

            <p className="mt-1 text-xs text-slate-500">
              Security reports generated for your environment
            </p>
          </div>

          <Clock className="h-5 w-5 text-slate-500" />
        </div>

        <div className="divide-y divide-white/5">
          {reports.map((report) => (
            <div
              key={report.id}
              className="flex flex-col gap-4 px-6 py-5 transition hover:bg-slate-800/30 md:flex-row md:items-center md:justify-between"
            >
              <div className="flex items-center gap-4">
                <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-cyan-400/10">
                  <FileText className="h-5 w-5 text-cyan-400" />
                </div>

                <div>
                  <h3 className="text-sm font-medium text-white">
                    {report.name}
                  </h3>

                  <p className="mt-1 text-xs text-slate-500">
                    {report.type} • {report.date}
                  </p>
                </div>
              </div>

              <div className="flex items-center gap-3">
                <span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs font-medium text-emerald-400">
                  {report.status}
                </span>

                <button
                  onClick={() => handleDownload(report)}
                  className="inline-flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-xs text-slate-300 transition hover:border-cyan-400/30 hover:bg-cyan-400/5 hover:text-cyan-400"
                >
                  <Download className="h-4 w-4" />
                  Download
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Generate Report Modal */}
      {showModal && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 px-4 backdrop-blur-sm"
          onClick={() => setShowModal(false)}
        >
          <div
            className="w-full max-w-md rounded-2xl border border-white/10 bg-slate-900 p-6 shadow-2xl"
            onClick={(event) => event.stopPropagation()}
          >
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-lg font-semibold text-white">
                  Generate Report
                </h2>

                <p className="mt-1 text-sm text-slate-500">
                  Select the type of report to generate.
                </p>
              </div>

              <button
                onClick={() => setShowModal(false)}
                className="rounded-lg p-2 text-slate-500 transition hover:bg-slate-800 hover:text-white"
              >
                <X className="h-5 w-5" />
              </button>
            </div>

            <div className="mt-6 space-y-3">
              {[
                "Security Overview",
                "Threat Analysis",
                "Activity Summary",
              ].map((type) => (
                <label
                  key={type}
                  className={`flex cursor-pointer items-center gap-3 rounded-xl border p-4 transition ${
                    reportType === type
                      ? "border-cyan-400/40 bg-cyan-400/5"
                      : "border-white/10 hover:bg-slate-800/50"
                  }`}
                >
                  <input
                    type="radio"
                    name="reportType"
                    value={type}
                    checked={reportType === type}
                    onChange={(event) =>
                      setReportType(event.target.value)
                    }
                    className="accent-cyan-400"
                  />

                  <span className="text-sm text-slate-300">
                    {type}
                  </span>
                </label>
              ))}
            </div>

            <button
              onClick={handleGenerateReport}
              className="mt-6 w-full rounded-xl bg-cyan-500 px-4 py-3 text-sm font-semibold text-slate-950 transition hover:bg-cyan-400"
            >
              Generate Report
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

export default Reports;